runtime: python39

env_variables:
  BASE_URL: https://hex.lukwam.dev
  CLIENT_ID: 521581281991-6fnqjpverd9js2r6ajvebv17se901job.apps.googleusercontent.com

handlers:
  - url: /styles\.css
    static_files: styles.css
    upload: styles.css

  - url: /images
    static_dir: images
