steps:

  - id: build-docker-image
    name: gcr.io/cloud-builders/docker
    dir: images/image2png
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/docker/image2png:$SHORT_SHA
      - .

  - id: tag-docker-image
    name: gcr.io/cloud-builders/docker
    dir: images/image2png
    args:
      - tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/docker/image2png:$SHORT_SHA
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/docker/image2png:latest

  - id: push-latest-image
    name: gcr.io/cloud-builders/docker
    dir: images/image2png
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/docker/image2png:latest

  - id: push-shortsha-image
    name: gcr.io/cloud-builders/docker
    dir: images/image2png
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/docker/image2png:$SHORT_SHA

  - id: deploy-run-service
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - image2png
      - --allow-unauthenticated
      - --ingress=internal
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/docker/image2png:$SHORT_SHA
      - --memory=1G
      - --region=${_REGION}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/docker/image2png:$SHORT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/docker/image2png:latest
