steps:

  - id: build-docker-image
    name: gcr.io/cloud-builders/docker
    dir: images/pdf2png
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/docker/pdf2png:$SHORT_SHA
      - .

  - id: tag-docker-image
    name: gcr.io/cloud-builders/docker
    dir: images/pdf2png
    args:
      - tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/docker/pdf2png:$SHORT_SHA
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/docker/pdf2png:latest

  - id: push-shortSHA-image
    name: gcr.io/cloud-builders/docker
    dir: images/pdf2png
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/docker/pdf2png:$SHORT_SHA
